blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: /issues/new?template=bug_report.yaml
    about: Report a bug with the required information and debug logs.
  - name: Feature Request
    url: /issues/new?template=feature_request.yaml
    about: Suggest a new feature or enhancement.
